name: Bygg pull request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: "16"
      - name: Maven version
        run: mvn --version
      - name: Build
        shell: bash
        run: |
          mvn verify -B -s .m2/settings.xml --file pom.xml -DtrimStackTrace=false
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
