name: Bygg og deploy

on:
  push:
    branches:
      - master         # Push events on master branch

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'maven'
      - name: Build & Deploy
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn jacoco:prepare-agent install -e --batch-mode --file pom.xml -Djacoco.destFile=$(pwd)/target/jacoco.exec
          echo "Deployed artifacts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
